version: "2"

linters:
  enable:
    - errcheck
    - exhaustive
    - govet
    - staticcheck
    - unused
  settings:
    staticcheck:
      checks:
        - all
        - -ST1000
        - -S1016

formatters:
  enable:
    - gofmt
